/////////////////////////signup API/////////////////
POST http://localhost:4000/api/admin/signup
Content-Type: application/json

{
    "name" : "hello world",
    "username" : "heyworld",
    "password" : "heyhello",
    "email" : "hello@world.com"
}

###

POST http://localhost:4000/api/admin/signup
Content-Type: application/json

{
    "name" : "book book",
    "username" : "allbook",
    "password" : "bookdetails",
    "email" : "book@details.com"
}

###

//////////////////////////////////login API//////////////////////////////////////
POST http://localhost:4000/api/admin/login
Content-Type: application/json

{
    "username" : "heyworld",
    "password" : "heyhello"
}

###


///////////////////////////////////add new book details////////////////////////////
POST http://localhost:4000/api/admin/add-new-book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIwOTY0NGY4NTg5OTMyMzQ3MTNkMTAiLCJpYXQiOjE2NjMzMzczNTEsImV4cCI6MTY2MzQyMzc1MX0.9OhLQUMYeqVJ_XYJEv2iPSGoednw5KilPz6J90NmOVY

{
  "Title": "Programming in C++",
  "Stock": 50,
  "Issue_date":"14-09-2022"
}

###

/////////////////////update book dtails//////////////////////////////////
PUT http://localhost:4000/api/admin/update-old-book/6320977df858993234713d15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIwOTY0NGY4NTg5OTMyMzQ3MTNkMTAiLCJpYXQiOjE2NjMzMzczNTEsImV4cCI6MTY2MzQyMzc1MX0.9OhLQUMYeqVJ_XYJEv2iPSGoednw5KilPz6J90NmOVY

{
  "Stock":49,
  "Issue_date": "13-09-2022"
}

###

//////////////////delete book details/////////////////////

DELETE http://localhost:4000/api/admin/delete-book/6320a5730d0ebc30142b45b0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIwOTY0NGY4NTg5OTMyMzQ3MTNkMTAiLCJpYXQiOjE2NjMzMzczNTEsImV4cCI6MTY2MzQyMzc1MX0.9OhLQUMYeqVJ_XYJEv2iPSGoednw5KilPz6J90NmOVY

###


///////////////////issue book/////////////////////////////
PUT http://localhost:4000/api/admin/issue-book/6320a5010d0ebc30142b45ac
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIwOTY0NGY4NTg5OTMyMzQ3MTNkMTAiLCJpYXQiOjE2NjMzMzczNTEsImV4cCI6MTY2MzQyMzc1MX0.9OhLQUMYeqVJ_XYJEv2iPSGoednw5KilPz6J90NmOVY

{
  "Issue_date" : "27-02-2000", 
  "Student_ID" : "6322bb2eed293de86ffe852d"
}

###