
//Student Sign up
POST http://localhost:4000/api/student/signup
Content-Type: application/json

{
  "name": "Hello Student",
  "username": "helloStudent",
  "password": "helloStudent",
  "email" : "helloStudent@gmail.com",
  "stream": "CSE",
  "year" : 4,
  "roll": 2022001
}

###

//Student login
POST http://localhost:4000/api/student/login
Content-Type: application/json

{
    "username" : "helloStudent",
    "password" : "helloStudent"
}

###


//update profile details
PUT http://localhost:4000/api/student/update-profile/6322bb2eed293de86ffe852d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIyYmIyZWVkMjkzZGU4NmZmZTg1MmQiLCJpYXQiOjE2NjM1NjM1NDIsImV4cCI6MTY2MzY0OTk0Mn0.LMVViz0wQzAVq7jMx5U4oATex16CcgWqdIi5w_U7YUo

{
  "name" : "Me Student"
}

###

//view all book details
GET http://localhost:4000/api/student/view-all-books
Content-Type: application/json


###

//view books by genre
GET http://localhost:4000/api/student/view-selected-book-genre/science
Content-Type: application/json


###

//view books by subgenre
GET http://localhost:4000/api/student/view-selected-book-subgenre/economics
Content-Type: application/json

###

//view books by publisher
GET http://localhost:4000/api/student/view-selected-book-publisher/Penguin
Content-Type: application/json


###

//view my issued books
GET http://localhost:4000/api/student/my-issued-books/6322bb2eed293de86ffe852d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzIyYmIyZWVkMjkzZGU4NmZmZTg1MmQiLCJpYXQiOjE2NjMzMzc1MjgsImV4cCI6MTY2MzQyMzkyOH0.EVQtNymvdesJf1AYsFi5rpobupfqZQQz7fHg69nnnVI


###